version: "3"
services: 
    app:
        build: 
            context: ./
            dockerfile: ./docker/Dockerfile.prod.https.auto
        container_name: rogo
        ports:
            - "80:80"
            - "443:443"