FROM node:latest AS builder

WORKDIR /usr/app

COPY . .

RUN yarn install

RUN yarn run build:prod

FROM nginx:alpine

COPY --from=builder /usr/app/build /usr/share/nginx/html

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

ENTRYPOINT ["nginx", "-g", "daemon off;"]
