FROM node:latest AS builder

WORKDIR /usr/app

COPY . .

RUN yarn install

RUN yarn run build:prod

FROM nginx:alpine

COPY --from=builder /usr/app/build /usr/share/nginx/html

COPY ./nginx/default.https.conf /etc/nginx/conf.d/default.conf

RUN mkdir /etc/nginx/ssl 

RUN chmod 700 /etc/nginx/ssl

COPY ./nginx/cert/cert.pem /etc/nginx/ssl/cert.pem

COPY ./nginx/cert/key.pem /etc/nginx/ssl/key.pem
